#!/bin/sh
set -eu

mode=${1:---report}
case "$mode" in
	--report|--strict) ;;
	*)
		echo "usage: $0 [--report|--strict]" >&2
		exit 2
		;;
esac

project_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
rgo_bin=${RGO_BIN:-"$project_root/rgo"}
gem_root=${RGO_GEM_ROOT:-}
timeout_seconds=${RGO_GEM_TIMEOUT:-45}
case_filter=${RGO_GEM_CASE:-}

if [ -z "$gem_root" ]; then
	echo "RGO_GEM_ROOT must point to a directory containing the extracted pinned gems." >&2
	echo "See scripts/gem_compat_manifest.txt for versions and archive checksums." >&2
	exit 2
fi
if [ ! -x "$rgo_bin" ]; then
	echo "RGo executable not found: $rgo_bin" >&2
	exit 2
fi

ruby_lib=
for lib_dir in "$gem_root"/*/lib; do
	[ -d "$lib_dir" ] || continue
	if [ -z "$ruby_lib" ]; then
		ruby_lib=$lib_dir
	else
		ruby_lib=$ruby_lib:$lib_dir
	fi
done
concurrent_nested="$gem_root/concurrent-ruby-1.3.7/lib/concurrent-ruby"
if [ -d "$concurrent_nested" ]; then
	ruby_lib=$ruby_lib:$concurrent_nested
fi
if [ -z "$ruby_lib" ]; then
	echo "No extracted gem lib directories found below: $gem_root" >&2
	exit 2
fi

tmp_dir=$(mktemp -d "${TMPDIR:-/tmp}/rgo-gem-gate.XXXXXX")
trap 'rm -rf "$tmp_dir"' EXIT HUP INT TERM

passed=0
failed=0

run_case() {
	name=$1
	source=$2
	expected=$3
	if [ -n "$case_filter" ] && [ "$name" != "$case_filter" ]; then
		return
	fi
	stdout_file="$tmp_dir/$name.stdout"
	stderr_file="$tmp_dir/$name.stderr"

	if RUBYLIB="$ruby_lib" GOMAXPROCS=1 timeout "$timeout_seconds" "$rgo_bin" -e "$source" >"$stdout_file" 2>"$stderr_file"; then
		actual=$(cat "$stdout_file")
		if [ "$actual" = "$expected" ]; then
			echo "PASS $name"
			passed=$((passed + 1))
			return
		fi
		detail="output: $actual"
	else
		detail=$(sed -n '1p' "$stderr_file")
		[ -n "$detail" ] || detail="process failed or timed out"
	fi

	echo "FAIL $name - $detail"
	failed=$((failed + 1))
}

run_case rack 'require "rack"; puts Rack.release' '3.2.6'
run_case rack_cors 'require "rack/cors"; require "rack/cors/version"; puts Rack::Cors::VERSION' '3.0.0'
run_case rackup 'require "rackup"; puts Rackup::VERSION' '2.3.1'
run_case rake 'require "rake"; puts Rake::VERSION' '13.4.2'
run_case minitest 'require "minitest"; puts Minitest::VERSION' '6.0.6'
run_case public_suffix 'require "public_suffix"; puts PublicSuffix::VERSION' '7.0.5'
run_case pry 'require "pry"; puts Pry::VERSION' '0.16.0'
run_case method_source 'require "method_source"; puts MethodSource.name' 'MethodSource'
run_case ast 'require "ast"; puts AST::Node.name' 'AST::Node'
run_case racc 'require "racc/parser.rb"; puts Racc::VERSION' '1.8.1'
run_case parser 'require "parser/current"; puts Parser::VERSION' '3.3.12.0'
run_case rainbow 'require "rainbow"; require "rainbow/version"; puts Rainbow::VERSION' '3.1.1'
run_case regexp_parser 'require "regexp_parser"; puts Regexp::Parser::VERSION' '2.12.0'
run_case parallel 'require "parallel"; puts Parallel::VERSION' '2.1.0'
run_case ruby_progressbar 'require "ruby-progressbar"; require "ruby-progressbar/version"; puts ProgressBar::VERSION' '1.13.0'
run_case unicode_emoji 'require "unicode/emoji"; puts Unicode::Emoji::VERSION' '4.2.0'
run_case unicode_display_width 'require "unicode/display_width"; puts Unicode::DisplayWidth::VERSION' '3.2.0'
run_case language_server_protocol 'require "language_server/protocol"; puts LanguageServer::Protocol::VERSION' '3.17.0.6'
run_case lint_roller 'require "lint_roller"; puts LintRoller::VERSION' '1.1.0'
run_case docile 'require "docile"; puts Docile::VERSION' '1.4.1'
run_case simplecov_html 'require "simplecov-html"; puts SimpleCov::Formatter::HTMLFormatter.name' 'SimpleCov::Formatter::HTMLFormatter'
run_case simplecov_json_formatter 'require "simplecov_json_formatter"; puts SimpleCov::Formatter::JSONFormatter.name' 'SimpleCov::Formatter::JSONFormatter'
run_case simplecov 'require "simplecov"; puts SimpleCov::VERSION' '1.0.3'
run_case yard 'require "yard"; puts YARD::VERSION' '0.9.45'
run_case kramdown 'require "kramdown"; puts Kramdown::VERSION' '2.5.2'
run_case kramdown_parser_gfm 'require "kramdown"; require "kramdown-parser-gfm"; puts Kramdown::Parser::GFM::VERSION' '1.1.0'
run_case csv 'require "csv"; puts CSV::VERSION' '3.3.6'
run_case rest_client 'require "rest-client"; puts RestClient::VERSION' '2.1.0'
run_case http_cookie 'require "http-cookie"; puts HTTP::Cookie::VERSION' '1.1.6'
run_case domain_name 'require "domain_name"; puts DomainName::VERSION' '0.6.20240107'
run_case mime_types 'require "mime/types"; puts MIME::Types::VERSION' '3.7.0'
run_case mime_types_data 'require "mime/types/data"; puts MIME::Types::Data::VERSION' '3.2026.0701'
run_case netrc 'require "netrc"; puts Netrc::VERSION' '0.11.0'
run_case http_accept 'require "http/accept"; puts HTTP::Accept::VERSION' '1.7.0'
run_case terminal_table 'require "terminal-table"; puts Terminal::Table::VERSION' '4.0.0'
run_case tty_spinner 'require "tty-spinner"; puts TTY::Spinner::VERSION' '0.9.3'
run_case tty_progressbar 'require "tty-progressbar"; puts TTY::ProgressBar::VERSION' '0.18.3'
run_case tty_cursor 'require "tty-cursor"; puts TTY::Cursor::VERSION' '0.7.1'
run_case tty_screen 'require "tty-screen"; puts TTY::Screen::VERSION' '0.8.2'
run_case strings_ansi 'require "strings-ansi"; puts Strings::ANSI::VERSION' '0.2.0'
run_case tty_prompt 'require "tty-prompt"; puts TTY::Prompt::VERSION' '0.23.1'
run_case pastel 'require "pastel"; puts Pastel::VERSION' '0.8.0'
run_case strings 'require "strings"; puts Strings::VERSION' '0.2.1'
run_case tty_reader 'require "tty-reader"; puts TTY::Reader::VERSION' '0.8.0'
run_case tty_color 'require "tty-color"; puts TTY::Color::VERSION' '0.5.2'
run_case wisper 'require "wisper"; puts Wisper::VERSION' '2.0.1'
run_case unicode_utils 'require "unicode_utils"; puts UnicodeUtils::VERSION' '1.4.0'
run_case vcr 'require "vcr"; puts VCR.version' '6.4.0'
run_case rack_cache 'require "rack/cache"; require "rack/cache/version"; puts Rack::Cache::VERSION' '1.17.0'
run_case roda 'require "roda"; puts Roda::RodaVersion' '3.106.0'
run_case diff_lcs 'require "diff/lcs"; puts Diff::LCS::VERSION' '2.0.0'
run_case memoist 'require "memoist"; puts Memoist::VERSION' '0.16.2'
run_case mocha 'require "mocha/api"; require "mocha/version"; puts Mocha::VERSION' '3.1.0'
run_case chronic 'require "chronic"; puts Chronic::VERSION' '0.10.2'
run_case dry_container 'require "dry/container"; require "dry/container/version"; puts Dry::Container::VERSION' '0.11.0'
run_case dry_auto_inject 'require "dry/auto_inject"; require "dry/auto_inject/version"; puts Dry::AutoInject::VERSION' '1.2.1'
run_case fugit 'require "fugit"; puts Fugit::VERSION' '1.13.0'
run_case ruby2_keywords 'require "ruby2_keywords"; puts :ok' 'ok'
run_case et_orbi 'require "et-orbi"; puts EtOrbi::VERSION' '1.4.0'
run_case raabro 'require "raabro"; puts Raabro::VERSION' '1.5.0'
run_case timecop 'require "timecop"; puts Timecop::VERSION' '0.9.11'
run_case database_cleaner_core 'require "database_cleaner/core"; puts DatabaseCleaner::VERSION' '2.1.0'
run_case shoulda_context 'require "shoulda-context"; puts Shoulda::Context::VERSION' '2.0.0'
run_case test_prof 'require "test_prof"; puts TestProf::VERSION' '1.6.3'
run_case memory_profiler 'require "memory_profiler"; puts MemoryProfiler::VERSION' '1.1.0'
run_case rspec_retry 'require "rspec/retry"; puts RSpec::Retry::VERSION' '0.6.2'
run_case climate_control 'require "climate_control"; puts ClimateControl::VERSION' '1.2.0'
run_case highline 'require "highline"; puts HighLine::VERSION' '3.1.2'
run_case dry_events 'require "dry/events"; require "dry/events/version"; puts Dry::Events::VERSION' '1.1.0'
run_case dry_matcher 'require "dry/matcher"; require "dry/matcher/version"; puts Dry::Matcher::VERSION' '1.0.0'
run_case dry_transaction 'require "dry/transaction"; require "dry/transaction/version"; puts Dry::Transaction::VERSION' '0.16.0'
run_case fuubar 'require "fuubar"; puts Fuubar.name' 'Fuubar'
run_case rspec_junit_formatter 'require "rspec_junit_formatter"; puts RSpecJUnitFormatter.name' 'RSpecJUnitFormatter'
run_case hana 'require "hana"; puts Hana.name' 'Hana'
run_case simpleidn 'require "simpleidn"; puts SimpleIDN.name' 'SimpleIDN'
run_case json_schemer 'require "json_schemer"; puts JSONSchemer.name' 'JSONSchemer'
run_case multi_json 'require "multi_json"; puts MultiJSON::VERSION' '1.21.1'
run_case json_schema 'require "json-schema"; puts JSON::Validator.name' 'JSON::Validator'
run_case prometheus_client 'require "prometheus/client"; puts Prometheus::Client.name' 'Prometheus::Client'
run_case octokit 'require "octokit"; puts Octokit::VERSION' '10.0.0'
run_case sawyer 'require "sawyer"; puts Sawyer::VERSION' '0.9.3'
run_case faraday_multipart 'require "faraday"; require "faraday/multipart"; puts Faraday::Multipart::VERSION' '1.2.0'
run_case multipart_post 'require "multipart/post"; require "multipart/post/version"; puts Multipart::Post::VERSION' '2.4.1'
run_case dry_system 'require "dry/system"; require "dry/system/version"; puts Dry::System::VERSION' '1.2.5'
run_case oauth2 'require "oauth2"; puts OAuth2::VERSION' '2.0.25'
run_case anonymous_loader 'require "anonymous_loader"; puts AnonymousLoader::VERSION' '0.1.3'
run_case auth_sanitizer 'require "auth/sanitizer"; puts Auth::Sanitizer::VERSION' '0.2.3'
run_case snaky_hash 'require "snaky_hash"; puts SnakyHash::VERSION' '2.0.7'
run_case version_gem 'require "version_gem"; puts VersionGem::VERSION' '1.1.14'
run_case graphql_client 'require "graphql/client"; puts GraphQL::Client.name' 'GraphQL::Client'
run_case net_ssh 'require "net/ssh"; puts Net::SSH::Version::CURRENT' '7.3.3'
run_case aws_sdk_s3 'require "aws-sdk-s3"; puts Aws::S3::GEM_VERSION' '1.228.0'
run_case aws_sdk_kms 'require "aws-sdk-kms"; puts Aws::KMS::GEM_VERSION' '1.130.0'
run_case prawn 'require "prawn"; puts Prawn::VERSION' '2.5.0'
run_case pdf_core 'require "pdf/core"; puts Gem.loaded_specs["pdf-core"].version' '0.10.0'
run_case ttfunk 'require "ttfunk"; puts Gem.loaded_specs["ttfunk"].version' '1.8.0'
run_case matrix 'require "matrix/version"; puts Matrix::VERSION' '0.4.3'
run_case addressable 'require "addressable/version"; puts Addressable::VERSION::STRING' '2.9.0'
run_case base64 'require "base64"; puts Base64::VERSION' '0.3.0'
run_case bcrypt 'require "bcrypt"; puts Gem.loaded_specs["bcrypt"].version' '3.1.22'
run_case benchmark_ips 'require "benchmark/ips"; puts Benchmark::IPS::VERSION' '2.15.1'
run_case bigdecimal 'require "bigdecimal"; puts BigDecimal::VERSION' '3.3.1'
run_case blueprinter 'require "blueprinter"; require "blueprinter/version"; puts Blueprinter::VERSION' '1.3.0'
run_case builder 'require "builder"; puts Builder::XmlMarkup.name' 'Builder::XmlMarkup'
run_case cancancan 'require "cancan"; puts CanCan::VERSION' '3.6.1'
run_case coderay 'require "coderay"; puts CodeRay::VERSION' '1.1.3'
run_case faker 'require "faker"; puts Faker::VERSION' '3.8.0'
run_case factory_bot 'require "factory_bot"; puts FactoryBot::VERSION' '6.6.0'
run_case fiber_storage 'require "fiber/storage/version"; puts Fiber::Storage::VERSION' '1.0.1'
run_case globalid 'require "globalid"; puts GlobalID::VERSION' '1.4.0'
run_case graphql 'require "graphql"; puts GraphQL::VERSION' '2.6.7'
run_case money 'require "money"; puts Money::VERSION' '7.0.2'
run_case omniauth 'require "omniauth"; require "omniauth/version"; puts OmniAuth::VERSION' '2.1.4'
run_case orm_adapter 'require "orm_adapter"; puts OrmAdapter::VERSION' '0.5.0'
run_case aasm 'require "aasm"; puts AASM::VERSION' '6.0.0'
run_case pagy 'require "pagy"; puts Pagy::VERSION' '43.6.1'
run_case pundit 'require "pundit"; puts Pundit::VERSION' '2.5.2'
run_case rubyzip 'require "zip"; puts Zip::VERSION' '3.4.1'
run_case rouge 'require "rouge"; puts Rouge.version' '5.0.0'
run_case sidekiq 'require "sidekiq"; puts Sidekiq::VERSION' '7.3.10'
run_case warden 'require "warden"; require "warden/version"; puts Warden::VERSION' '1.2.9'
run_case webmock 'require "webmock"; require "webmock/version"; puts WebMock::VERSION' '3.26.2'
run_case active_job 'require "active_job"; puts ActiveJob.version' '8.1.2'
run_case active_model 'require "active_model"; puts ActiveModel.version' '8.1.2'
run_case active_record 'require "active_record"; puts ActiveRecord.version' '8.1.2'
run_case action_pack 'require "action_controller"; puts ActionPack.version' '8.1.2'
run_case action_view 'require "action_view"; puts ActionView.version' '8.1.2'
run_case activerecord_import 'require "activerecord-import"; require "activerecord-import/version"; puts ActiveRecord::Import::VERSION' '2.2.0'
run_case audited 'require "audited"; require "audited/version"; puts Audited::VERSION' '5.8.0'
run_case dotenv 'require "dotenv"; puts Dotenv::VERSION' '3.2.0'
run_case hashie 'require "hashie"; puts Hashie::VERSION' '5.1.0'
run_case hashdiff 'require "hashdiff"; puts Hashdiff::VERSION' '1.2.1'
run_case i18n 'require "i18n"; puts I18n::VERSION' '1.15.2'
run_case jwt 'require "jwt"; puts JWT::VERSION::STRING' '3.2.0'
run_case httparty 'require "httparty"; puts HTTParty::VERSION' '0.24.2'
run_case mini_mime 'require "mini_mime"; puts MiniMime::VERSION' '1.1.5'
run_case mail 'require "mail"; puts Mail::VERSION::STRING' '2.9.1'
run_case marcel 'require "marcel"; puts Marcel::VERSION' '1.2.1'
run_case multi_xml 'require "multi_xml"; require "multi_xml/version"; puts MultiXml::VERSION' '0.9.1'
run_case net_imap 'require "net/imap"; puts Net::IMAP::VERSION' '0.6.6'
run_case net_pop 'require "net/pop"; puts Net::POP::VERSION' '0.1.2'
run_case net_protocol 'require "net/protocol"; puts Net::Protocol.name' 'Net::Protocol'
run_case net_smtp 'require "net/smtp"; puts Net::SMTP::VERSION' '0.5.1'
run_case rexml 'require "rexml/document"; puts REXML::VERSION' '3.4.4'
run_case reline 'require "reline"; puts Reline::VERSION' '0.6.3'
run_case concurrent_ruby 'require "concurrent"; puts Concurrent::VERSION' '1.3.7'
run_case connection_pool 'require "connection_pool"; puts ConnectionPool::VERSION' '2.5.4'
run_case erb 'require "erb"; puts ERB.version' '6.0.6'
run_case thor 'require "thor/version"; puts Thor::VERSION' '1.5.0'
run_case tzinfo 'require "tzinfo"; puts TZInfo::VERSION' '2.0.6'
run_case zeitwerk 'require "zeitwerk"; puts Zeitwerk::VERSION' '2.8.2'
run_case active_support 'require "active_support"; puts ActiveSupport.version' '8.1.2'
run_case forwardable 'require "forwardable"; puts Forwardable::VERSION' '1.4.0'
run_case uri 'require "uri"; puts URI::VERSION' '1.1.1'
run_case net_http 'require "net/http"; puts Net::HTTP::VERSION' '0.9.1'
run_case net_http_persistent 'require "net/http/persistent"; puts Net::HTTP::Persistent::VERSION' '4.0.8'
run_case webrick 'require "webrick"; puts WEBrick::VERSION' '1.9.2'
run_case faraday 'require "faraday"; puts Faraday::VERSION' '2.14.3'
run_case faraday_net_http 'require "faraday"; require "faraday/net_http"; puts Faraday::NetHttp::VERSION' '3.4.4'
run_case faraday_retry 'require "faraday/retry"; puts Faraday::Retry::VERSION' '2.4.0'
run_case rack_attack 'require "rack/attack"; require "rack/attack/version"; puts Rack::Attack::VERSION' '6.8.0'
run_case request_store 'require "request_store"; puts RequestStore::VERSION' '1.7.0'
run_case liquid 'require "liquid"; puts Liquid::VERSION' '5.13.0'
run_case slim 'require "slim"; puts Slim::VERSION' '5.2.2'
run_case haml 'require "haml"; puts Haml::VERSION' '7.2.2'
run_case erubi 'require "erubi"; puts Erubi::VERSION' '1.13.1'
run_case jbuilder 'require "jbuilder"; puts Jbuilder::VERSION' '2.15.1'
run_case temple 'require "temple"; puts Temple::VERSION' '0.10.4'
run_case enumerize 'require "enumerize"; puts Enumerize::VERSION' '2.8.1'
run_case dry_struct 'require "dry-struct"; puts Dry::Struct::VERSION' '1.8.1'
run_case state_machines 'require "state_machines"; puts StateMachines::VERSION' '0.201.0'
run_case state_machines_activemodel 'require "state_machines-activemodel"; puts StateMachines::Integrations::ActiveModel::VERSION' '0.200.0'
run_case state_machines_activerecord 'require "state_machines-activerecord"; puts StateMachines::Integrations::ActiveRecord::VERSION' '0.200.0'
run_case ransack 'require "ransack"; puts Ransack::VERSION' '4.4.1'
run_case friendly_id 'require "friendly_id"; require "friendly_id/version"; puts FriendlyId::VERSION' '5.7.0'
run_case discard 'require "discard"; puts Discard::VERSION' '2.0.0'
run_case paper_trail 'require "active_record"; require "paper_trail"; puts PaperTrail::VERSION::STRING' '17.0.0'
run_case counter_culture 'require "active_record"; require "counter_culture"; puts CounterCulture::VERSION' '3.14.0'
run_case logger 'require "logger"; puts Logger::VERSION' '1.7.0'
run_case rspec 'require "rspec/version"; puts RSpec::Version::STRING' '3.13.2'
run_case rspec_core 'require "rspec/core/version"; puts RSpec::Core::Version::STRING' '3.13.6'
run_case rspec_expectations 'require "rspec/expectations/version"; puts RSpec::Expectations::Version::STRING' '3.13.5'
run_case rspec_mocks 'require "rspec/mocks/version"; puts RSpec::Mocks::Version::STRING' '3.13.8'
run_case rspec_support 'require "rspec/support/version"; puts RSpec::Support::Version::STRING' '3.13.7'
run_case dry_core 'require "dry/core"; puts Dry::Core::VERSION' '1.2.0'
run_case dry_configurable 'require "dry/configurable"; require "dry/configurable/version"; puts Dry::Configurable::VERSION' '1.4.0'
run_case dry_inflector 'require "dry/inflector"; puts Dry::Inflector::VERSION' '1.3.1'
run_case dry_initializer 'require "dry/initializer"; require "dry/initializer/version"; puts Dry::Initializer::VERSION' '3.2.0'
run_case dry_logic 'require "dry/logic"; require "dry/logic/version"; puts Dry::Logic::VERSION' '1.6.0'
run_case dry_monads 'require "dry/monads"; require "dry/monads/version"; puts Dry::Monads::VERSION' '1.10.0'
run_case dry_types 'require "dry/types"; puts Dry::Types::VERSION' '1.9.1'
run_case dry_schema 'require "dry/schema"; require "dry/schema/version"; puts Dry::Schema::VERSION' '1.16.0'
run_case dry_validation 'require "dry/validation"; require "dry/validation/version"; puts Dry::Validation::VERSION' '1.11.1'
run_case devise 'require "devise"; require "devise/version"; puts Devise::VERSION' '5.0.4'
run_case json_generate 'require "json"; puts JSON.generate({a: 1, items: [true, nil, 1.5]})' '{"a":1,"items":[true,null,1.5]}'
run_case crack 'require "crack"; puts Crack::VERSION' '1.0.1'
run_case kaminari_core 'require "kaminari/core"; require "kaminari/core/version"; puts Kaminari::Core::VERSION' '1.2.2'
run_case aws_eventstream 'require "aws-eventstream"; puts Aws::EventStream::Encoder.name' 'Aws::EventStream::Encoder'
run_case aws_partitions 'require "aws-partitions"; puts Aws::Partitions::EndpointProvider.name' 'Aws::Partitions::EndpointProvider'
run_case aws_sdk_core 'require "aws-sdk-core"; puts Aws::CORE_GEM_VERSION' '3.254.0'
run_case aws_sigv4 'require "aws-sigv4"; puts Aws::Sigv4::VERSION' '1.12.1'
run_case excon 'require "excon"; puts Excon::VERSION' '1.6.0'
run_case jmespath 'require "jmespath"; puts JMESPath::VERSION' '1.6.2'
run_case redis_namespace 'require "redis-namespace"; puts Redis::Namespace::VERSION' '1.11.0'
run_case semantic_logger 'require "semantic_logger"; puts SemanticLogger::VERSION' '5.1.0'
run_case sprockets 'require "sprockets"; puts Sprockets::VERSION' '4.2.2'
run_case sorbet_runtime 'require "sorbet-runtime"; puts Gem.loaded_specs["sorbet-runtime"].version' '0.6.13371'

run_case rack_escape 'require "rack"; puts Rack::Utils.escape("ruby 1/go")' 'ruby+1%2Fgo'
run_case rack_nested_query 'require "rack"; query = Rack::Utils.parse_nested_query("user[name]=ruby&tags[]=vm&tags[]=go"); puts [query["user"]["name"], query["tags"].join(",")].join(":")' 'ruby:vm,go'
run_case rack_mock_request 'require "rack/mock"; app = ->(env) { [200, {"content-type" => "text/plain"}, [env["PATH_INFO"] + ":" + env["QUERY_STRING"]]] }; response = Rack::MockRequest.new(app).get("/hello?x=1"); puts [response.status, response.body].join(":")' '200:/hello:x=1'
run_case rack_builder 'require "rack"; require "rack/mock"; app = Rack::Builder.new { run ->(env) { [200, {"content-type" => "text/plain"}, [env["PATH_INFO"]]] } }.to_app; response = Rack::MockRequest.new(app).get("/built"); puts [response.status, response.body].join(":")' '200:/built'
run_case rackup_app 'require "rackup"; require "rack/mock"; app = ->(env) { [200, {"content-type" => "text/plain"}, [env["PATH_INFO"]]] }; server = Rackup::Server.new(app: app, environment: "none"); status, headers, body = server.app.call(Rack::MockRequest.env_for("/rackup")); puts [Rackup::VERSION, status, headers["content-type"], body.join].join("|")' '2.3.1|200|text/plain|/rackup'
run_case webrick_request 'require "webrick"; require "stringio"; request = WEBrick::HTTPRequest.new(WEBrick::Config::HTTP); request.parse(StringIO.new("GET /hello?x=1 HTTP/1.1\r\nHost: example.org\r\nUser-Agent: rgo\r\n\r\n")); puts [WEBrick::VERSION, request.request_method, request.path, request.query["x"], request.host, request["user-agent"]].join("|")' '1.9.2|GET|/hello|1|example.org|rgo'
run_case net_http_persistent_setup 'require "net/http/persistent"; proxy = URI("http://user:pass@proxy.example:8080?no_proxy=internal.example"); client = Net::HTTP::Persistent.new(name: "rgo-gate", proxy: proxy, pool_size: 2); client.headers["User-Agent"] = "rgo"; request = client.request_setup(URI("http://example.org/items?q=1")); puts [Net::HTTP::Persistent::VERSION, client.name, client.proxy_uri.hostname, client.proxy_uri.port, client.no_proxy.join(","), request.method, request.path, request["User-Agent"], request["Connection"], request["Keep-Alive"], client.escape("ruby go")].join("|")' '4.0.8|rgo-gate|proxy.example|8080|internal.example|GET|/items?q=1|rgo|keep-alive|30|ruby+go'
run_case railties 'require "rails"; puts Rails.version' '8.1.2'
run_case responders 'require "responders"; require "responders/version"; puts Responders::VERSION' '3.2.0'
run_case tsort 'require "tsort"; puts TSort::VERSION' '0.2.0'
run_case rack_test_session 'require "rack/test"; app = ->(env) { [200, {"content-type" => "text/plain"}, [env["PATH_INFO"]]] }; session = Rack::Test::Session.new(Rack::MockSession.new(app)); response = session.get("/health"); puts [Rack::Test::VERSION, response.status, response.body].join("|")' '2.2.0|200|/health'
run_case rack_cors_preflight 'require "rack"; require "rack/mock"; require "rack/cors"; app = Rack::Cors.new(->(_env) { [200, {"content-type" => "text/plain"}, ["ok"]] }) { allow { origins "https://app.example"; resource "/api/*", headers: :any, methods: [:get, :options] } }; response = Rack::MockRequest.new(app).options("/api/items", "HTTP_ORIGIN" => "https://app.example", "HTTP_ACCESS_CONTROL_REQUEST_METHOD" => "GET"); puts [response.status, response["access-control-allow-origin"], response["access-control-allow-methods"].include?("GET")].join("|")' '200|https://app.example|true'
run_case sinatra_dynamic_route 'require "sinatra/base"; require "rack/mock"; class RGoGemGateApp < Sinatra::Base; set :host_authorization, {permitted_hosts: ["example.org"]}; set :show_exceptions, false; get("/users/:id") { "user=#{params[:id]}" }; end; response = Rack::MockRequest.new(RGoGemGateApp).get("/users/42", "HTTP_HOST" => "example.org"); puts [response.status, response.body].join(":")' '200:user=42'
run_case redis_client_config 'require "redis"; client = Redis.new(url: "redis://cache.example:6380/2", timeout: 1.5); connection = client.connection; puts [Redis::VERSION, connection[:host], connection[:port], connection[:db], client.id].join(":")' '5.4.1:cache.example:6380:2:redis://cache.example:6380/2'
run_case redis_commandstats_transform 'require "redis"; class RGoGemGateRedis < Redis; private; def send_command(command); yield "cmdstat_get:calls=2,usec=4\r\n"; end; end; info = RGoGemGateRedis.new.info("commandstats"); puts [info["get"]["calls"], info["get"]["usec"]].join(":")' '2:4'
run_case sequel_mock_sql 'require "sequel/core"; require "sequel/adapters/mock"; database = Sequel.mock; puts database[:items].where(id: 1).sql' 'SELECT * FROM items WHERE (id = 1)'
run_case sequel_model_mock 'require "sequel"; database = Sequel.mock(columns: [:id, :name], fetch: [{id: 1, name: "Ada"}]); model = Class.new(Sequel::Model(database[:items])); item = model.first; puts [Sequel::VERSION, model.where(id: 1).sql, item.id, item.name].join("|")' '5.106.0|SELECT * FROM items WHERE (id = 1)|1|Ada'
run_case sequel_model_crud 'require "sequel"; database = Sequel.mock(columns: [:id, :name], fetch: [{id: 7, name: "Ada"}], autoid: 7, numrows: 1); model = Class.new(Sequel::Model(database[:items])); item = model.create(name: "Ada"); item.update(name: "Grace"); item.delete; puts [item.id, item.name, database.sqls.map { |sql| sql.split.first }.join(",")].join("|")' '7|Grace|SELECT,BEGIN,INSERT,SELECT,COMMIT,BEGIN,UPDATE,COMMIT,DELETE'
run_case jwt_hs256 'require "jwt"; token = JWT.encode({sub: "42", admin: true}, "secret", "HS256"); payload, header = JWT.decode(token, "secret", true, algorithm: "HS256"); puts [payload["sub"], payload["admin"], header["alg"]].join("|")' '42|true|HS256'
run_case hashie_mash 'require "hashie"; data = Hashie::Mash.new(user: {name: "Ada", roles: ["admin"]}); puts [data.user.name, data.user.roles.first].join("|")' 'Ada|admin'
run_case builder_xml 'require "builder"; xml = Builder::XmlMarkup.new; puts xml.person { xml.id(7); xml.name("Ada") }' '<person><id>7</id><name>Ada</name></person>'
run_case money_arithmetic 'require "money"; total = Money.new(12_345, "USD") + Money.new(55, "USD"); puts [Money::VERSION, total.cents, total.currency.iso_code, (total * 2).cents].join("|")' '7.0.2|12400|USD|24800'
run_case aasm_transition 'require "aasm"; class RGoGemGateJob; include AASM; aasm do; state :sleeping, initial: true; state :running; event(:run) { transitions from: :sleeping, to: :running }; end; end; job = RGoGemGateJob.new; before = job.aasm.current_state; allowed = job.may_run?; changed = job.run; puts [AASM::VERSION, before, allowed, changed, job.aasm.current_state].join("|")' '6.0.0|sleeping|true|true|running'
run_case pundit_authorize 'require "pundit"; class RGoGemGateUser; attr_reader :admin; def initialize(admin); @admin = admin; end; def admin?; @admin; end; end; class RGoGemGatePost; end; class RGoGemGatePostPolicy; def initialize(user, record); @user = user; @record = record; end; def update?; @user.admin?; end; end; post = RGoGemGatePost.new; allowed = Pundit.authorize(RGoGemGateUser.new(true), post, :update?); denied = begin; Pundit.authorize(RGoGemGateUser.new(false), post, :update?); false; rescue Pundit::NotAuthorizedError; true; end; puts [Pundit::VERSION, allowed.class.name, denied].join("|")' '2.5.2|RGoGemGatePost|true'
run_case rubyzip_memory 'require "zip"; buffer = Zip::OutputStream.write_buffer { |zip| zip.put_next_entry("hello.txt"); zip.write("hello rubyzip") }; buffer.rewind; input = Zip::InputStream.new(buffer); entry = input.get_next_entry; puts [Zip::VERSION, entry.name, input.read(entry.size)].join("|")' '3.4.1|hello.txt|hello rubyzip'
run_case rouge_highlight 'require "rouge"; tokens = Rouge::Lexers::Ruby.new.lex(%q{puts "hi"}).to_a; html = Rouge.highlight(%q{puts "hi"}, "ruby", "html"); puts [Rouge.version, tokens.length, tokens.first[0].shortname, html.include?(%q{class="nb"}), html.include?("hi")].join("|")' '5.0.0|5|nb|true|true'
run_case coderay_highlight 'require "coderay"; proxy = CodeRay.scan(%q{puts "hi"}, :ruby); tokens = proxy.tokens; html = proxy.html(wrap: :span); puts [CodeRay::VERSION, tokens.class.name, tokens.length > 0, html.include?(%q{class="string"}), html.include?("hi")].join("|")' '1.1.3|CodeRay::Tokens|true|true|true'
run_case pry_code_highlight 'require "pry"; code = Pry::Code.new("x = 1\ny = x + 2\n"); text = code.to_s; highlighted = Pry::SyntaxHighlighter.highlight(text); puts [Pry::VERSION, CodeRay::VERSION, text.lines.count, text.include?("y = x + 2"), highlighted.include?("y")].join("|")' '0.16.0|1.1.3|2|true|true'
run_case method_source_extract 'require "pry"; require "method_source"; incomplete = MethodSource.complete_expression?("def x\n"); complete = MethodSource.complete_expression?("def x\n1\nend\n"); direct = MethodSource.method(:source_helper).source; pry = Pry::Method.from_obj(MethodSource, :source_helper).source; puts [incomplete, complete, direct.lines.length, direct.include?("expression_at"), pry == direct].join("|")' 'false|true|8|true|true'
run_case kramdown_html 'require "kramdown"; html = Kramdown::Document.new("# Hello\n\nThis *is* [RGo](https://example.test).\n").to_html; puts [html.include?("<h1 id=\"hello\">Hello</h1>"), html.include?("<em>is</em>"), html.include?("<a href=\"https://example.test\">RGo</a>")].join("|")' 'true|true|true'
run_case kramdown_gfm 'require "kramdown"; require "kramdown-parser-gfm"; html = Kramdown::Document.new("~~old~~\n", input: "GFM").to_html; puts [Kramdown::Parser::GFM::VERSION, html.strip].join("|")' '1.1.0|<p><del>old</del></p>'
run_case csv_headers 'require "csv"; row = CSV.parse("name,score\nAda,42\n", headers: true).first; puts [CSV::VERSION, row["name"], row["score"], row.to_h == {"name" => "Ada", "score" => "42"}].join("|")' '3.3.6|Ada|42|true'
run_case http_accept_quality 'require "http/accept"; media = HTTP::Accept::MediaTypes.parse("text/html;q=0.5, application/json;q=0.9"); puts [HTTP::Accept::VERSION, media.first.mime_type, media.last.mime_type].join("|")' '1.7.0|application/json|text/html'
run_case http_cookie_jar 'require "http-cookie"; jar = HTTP::CookieJar.new; uri = URI("https://example.test/path"); jar.parse("session=abc; Path=/; Secure; HttpOnly", uri); cookie = jar.cookies(uri).first; puts [cookie.name, cookie.value, cookie.secure?, cookie.httponly?].join("|")' 'session|abc|true|true'
run_case mime_types_lookup 'require "mime/types"; html = MIME::Types.type_for("index.html").first; json = MIME::Types["application/json"].first; puts [html.content_type, html.extensions.include?("html"), json.media_type, json.sub_type].join("|")' 'text/html|true|application|json'
run_case netrc_parse 'require "netrc"; netrc = Netrc.new("memory", Netrc.parse(Netrc.lex(["machine example.test login ada password secret\n"]))); puts [Netrc::VERSION, *netrc["example.test"]].join("|")' '0.11.0|ada|secret'
run_case rest_client_webmock 'require "webmock"; require "rest-client"; include WebMock::API; WebMock.enable!; stub_request(:get, "http://example.test/items?q=rgo").with(headers: {"Accept" => "application/json"}).to_return(status: 200, body: "{\"ok\":true}", headers: {"Content-Type" => "application/json", "Set-Cookie" => "sid=abc; Path=/"}); response = RestClient.get("http://example.test/items", params: {q: "rgo"}, accept: :json); puts [response.code, response.body, response.headers[:content_type], response.cookies["sid"]].join("|")' '200|{"ok":true}|application/json|abc'
run_case terminal_table_render 'require "terminal-table"; table = Terminal::Table.new(headings: ["Name", "Score"], rows: [["Ada", 42], ["一", 7]]); table.align_column(1, :right); text = table.to_s; puts [text.include?("| Ada  |    42 |"), text.include?("| 一   |     7 |"), text.lines.first.chomp == "+------+-------+"].join("|")' 'true|true|true'
run_case tty_cursor_sequences 'require "tty-cursor"; puts [TTY::Cursor.hide == "\e[?25l", TTY::Cursor.move_to(2, 3) == "\e[4;3H", TTY::Cursor.move(-2, 3) == "\e[2D\e[3A"].join("|")' 'true|true|true'
run_case tty_spinner_manual 'require "tty-spinner"; class RGoTTYOutput; attr_reader :string; def initialize; @string = ""; end; def tty?; true; end; def print(value); @string << value.to_s; end; def flush; self; end; end; output = RGoTTYOutput.new; spinner = TTY::Spinner.new("[:spinner] Work :item", frames: ["a", "b"], output: output); spinner.update(item: "A"); first = spinner.spin; spinner.success("Done"); puts [first, spinner.done?, spinner.success?, output.string.include?("[✔] Work A Done")].join("|")' '[a] Work A|true|true|true'
run_case tty_progressbar_render 'require "tty-progressbar"; class RGoTTYOutput; attr_reader :string; def initialize; @string = ""; end; def tty?; true; end; def print(value); @string << value.to_s; end; def flush; self; end; end; output = RGoTTYOutput.new; bar = TTY::ProgressBar.new(":bar :percent", total: 2, width: 10, frequency: 0, output: output); bar.start; bar.advance; bar.advance; puts [bar.current, bar.complete?, output.string.include?("100%"), TTY::ProgressBar.display_columns("A一")].join("|")' '2|true|true|3'
run_case pastel_decorate 'require "pastel"; pastel = Pastel.new(enabled: true); colored = pastel.red.bold("ruby"); puts [colored == "\e[31;1mruby\e[0m", pastel.strip(colored)].join("|")' 'true|ruby'
run_case strings_layout 'require "strings"; aligned = Strings::Align.align_right("一", 4); truncated = Strings::Truncate.truncate("A一BC", 4); wrapped = Strings::Wrap.wrap("Some longish text", 8); puts [aligned == "  一", truncated == "A一…", wrapped == "Some \nlongish \ntext"].join("|")' 'true|true|true'
run_case unicode_utils_text 'require "unicode_utils"; graphemes = UnicodeUtils.each_grapheme("a\r\nb").to_a; puts [UnicodeUtils.char_name("A"), UnicodeUtils.upcase("Straße"), UnicodeUtils.display_width("A一"), graphemes == ["a", "\r\n", "b"]].join("|")' 'LATIN CAPITAL LETTER A|STRASSE|3|true'
run_case wisper_broadcast 'require "wisper"; klass = Class.new { include Wisper::Publisher; def go(value); broadcast(:done, value); end }; events = []; listener = Object.new; listener.define_singleton_method(:done) { |value| events << value }; publisher = klass.new; publisher.subscribe(listener); publisher.go(42); puts [Wisper::VERSION, events].join("|")' '2.0.1|42'
run_case tty_prompt_interactions 'require "tty/prompt/test"; ask = TTY::Prompt::Test.new(enable_color: false); ask.input << "bad\nuser@example.com\n"; ask.input.rewind; email = ask.ask("Email?", validate: :email); confirm = TTY::Prompt::Test.new(enable_color: false); confirm.input << "y\n"; confirm.input.rewind; yes = confirm.yes?("Continue?"); menu = TTY::Prompt::Test.new(enable_color: false); menu.input << "\e[B\r"; menu.input.rewind; selected = menu.select("Pick?", ["red", "green", "blue"]); puts [email, ask.output.string.include?("invalid"), yes, selected, menu.output.string.include?("green")].join("|")' 'user@example.com|true|true|green|true'
run_case vcr_replay 'require "tmpdir"; require "json"; require "net/http"; require "vcr"; body = Dir.mktmpdir("rgo-vcr") do |directory|; cassette = {"http_interactions"=>[{"request"=>{"method"=>"get", "uri"=>"http://example.test/items", "body"=>{"encoding"=>"UTF-8", "string"=>""}, "headers"=>{}}, "response"=>{"status"=>{"code"=>200, "message"=>"OK"}, "headers"=>{"Content-Type"=>["text/plain"]}, "body"=>{"encoding"=>"UTF-8", "string"=>"cached-body"}, "http_version"=>nil}, "recorded_at"=>"Thu, 02 Jan 2020 03:04:05 GMT"}], "recorded_with"=>"VCR 6.4.0"}; File.write(File.join(directory, "sample.json"), JSON.generate(cassette)); VCR.configure { |config| config.cassette_library_dir = directory; config.hook_into :webmock }; VCR.use_cassette("sample", record: :none, serialize_with: :json) { Net::HTTP.get(URI("http://example.test/items")) }; end; puts [VCR.version, body, VCR.current_cassette.nil?].join("|")' '6.4.0|cached-body|true'
run_case rack_cache_hit 'require "rack/cache"; require "rack/mock"; calls = 0; app = ->(_env) { calls += 1; [200, {"content-type"=>"text/plain", "cache-control"=>"public, max-age=60"}, ["body-#{calls}"]] }; request = Rack::MockRequest.new(Rack::Cache.new(app)); first = request.get("/items"); second = request.get("/items"); puts [first.status, first.body, second.body, calls].join("|")' '200|body-1|body-1|1'
run_case roda_dynamic_route 'require "roda"; require "rack/mock"; app = Class.new(Roda) { route { |request| request.on("users", Integer) { |id| request.get { "user=#{id}" } } } }; response = Rack::MockRequest.new(app).get("/users/42"); puts [response.status, response.body].join("|")' '200|user=42'
run_case diff_lcs_patch 'require "diff/lcs"; old = %w[a b c]; hunks = Diff::LCS.diff(old, %w[a x c d]); changes = hunks.flat_map { |hunk| hunk }.map { |change| [change.action, change.position, change.element].join(":") }; patched = Diff::LCS.patch!(old.dup, hunks); puts [changes.join(","), patched.join].join("|")' '-:1:b,+:1:x,+:3:d|axcd'
run_case memoist_cache_lifecycle 'require "memoist"; klass = Class.new { extend Memoist; attr_reader :calls; def initialize; @calls = 0; end; def compute(value); @calls += 1; value * 2; end; memoize :compute }; probe = klass.new; values = [probe.compute(3), probe.compute(3), probe.compute(4)]; probe.flush_cache(:compute); values << probe.compute(3); puts [values.join(","), probe.calls].join("|")' '6,6,8,6|3'
run_case mocha_expectation 'require "mocha/api"; include Mocha::API; mocha_setup; service = mock("service"); service.expects(:call).with(21).returns(42); value = service.call(21); mocha_verify; mocha_teardown; puts value' '42'
run_case chronic_natural_time 'require "chronic"; value = Chronic.parse("next monday at noon", now: Time.local(2026, 7, 30, 9, 0, 0)); puts value.strftime("%F %T")' '2026-08-03 12:00:00'
run_case dry_container_resolution 'require "dry/container"; container = Dry::Container.new; calls = 0; container.register("service", memoize: true) { calls += 1; ->(value) { value * 2 } }; first = container["service"]; second = container.resolve("service"); puts [first.call(21), first.equal?(second), calls, container.key?("service")].join("|")' '42|true|1|true'
run_case dry_auto_inject_resolution 'require "dry/container"; require "dry/auto_inject"; container = Dry::Container.new; container.register("service", ->(value) { value * 2 }); import = Dry::AutoInject(container); klass = Class.new do; include import["service"]; def call(value); service.call(value); end; end; puts [klass.new.call(21), klass.new(service: ->(value) { value + 1 }).call(21)].join("|")' '42|22'
run_case fugit_cron_next_time 'require "fugit"; cron = Fugit.parse_cron("*/15 * * * *"); value = cron.next_time(Time.utc(2026, 7, 30, 10, 7, 0)); puts [cron.class.name, value.year, value.month, value.day, value.hour, value.min, value.sec].join("|")' 'Fugit::Cron|2026|7|30|10|15|0'
run_case timecop_freeze 'require "timecop"; frozen = Time.local(2026, 7, 30, 12, 34, 56); inside = Timecop.freeze(frozen) { [Time.now, Date.today, Process.clock_gettime(Process::CLOCK_MONOTONIC)] }; puts [inside[0].strftime("%F %T"), inside[1], inside[2].is_a?(Float), Time.now != frozen].join("|")' '2026-07-30 12:34:56|2026-07-30|true|true'
run_case database_cleaner_lifecycle 'require "database_cleaner/core"; events = []; strategy = Class.new(DatabaseCleaner::Strategy) { define_method(:initialize) { |items| @items = items }; define_method(:start) { @items << :start }; define_method(:clean) { @items << :clean } }.new(events); cleaner = DatabaseCleaner::Cleaner.new(:sample); cleaner.strategy = strategy; value = cleaner.cleaning { events << :body; 42 }; puts [value, events.join(","), cleaner.strategy.equal?(strategy)].join("|")' '42|start,body,clean|true'
run_case shoulda_assertions 'require "minitest"; Minitest.seed = 1234; require "shoulda-context"; klass = Class.new(Minitest::Test) do; context "collections" do; setup { @left = [:a, :b, :a] }; should("match") { safe_assert_block("must pass") { true }; assert_same_elements(@left, [:b, :a, :a]) }; end; end; name = klass.runnable_methods.grep(/collections should match/).first; result = klass.new(name).run; puts [name.include?("collections should match"), result.passed?, result.assertions, result.failures.length].join("|")' 'true|true|10|0'
run_case test_prof_core 'require "test_prof"; require "test_prof/utils/sized_ordered_set"; set = TestProf::Utils::SizedOrderedSet.new(3); [4, 1, 3, 2, 5].each { |value| set << value }; before = TestProf.now; after = TestProf.now; puts [set.to_a.join(","), set.size, after >= before, Process.class].join("|")' '5,4,3|3|true|Module'
run_case climate_control_modify 'require "climate_control"; ENV["RGO_CLIMATE"] = "before"; inside = ClimateControl.modify(RGO_CLIMATE: "inside", RGO_ADDED: "yes") { [ENV["RGO_CLIMATE"], ENV["RGO_ADDED"]] }; puts [*inside, ENV["RGO_CLIMATE"], ENV["RGO_ADDED"].nil?].join("|")' 'inside|yes|before|true'
run_case highline_stringio 'require "stringio"; require "highline"; input = StringIO.new("42\n"); output = StringIO.new; value = HighLine.new(input, output).ask("Number? ", Integer); puts [value, value.class, output.string.include?("Number?")].join("|")' '42|Integer|true'
run_case rspec_retry_second_attempt 'require "stringio"; require "rspec/retry"; require "rspec/expectations"; attempts = 0; RSpec.configure { |config| config.default_retry_count = 2 }; RSpec.describe("retry gate") { it("passes on its second attempt") { attempts += 1; expect(attempts).to eq(2) } }; status = RSpec::Core::Runner.run([], $stderr, StringIO.new); puts [status, attempts, attempts == 2].join("|")' '0|2|true'
run_case memory_profiler_allocations 'require "memory_profiler"; report = MemoryProfiler.report { 100.times { "rgo-memory-marker" } }; strings = report.allocated_objects_by_class.find { |entry| entry[:data] == "String" }; puts [report.total_allocated >= 100, strings[:count], report.total_allocated_memsize > 0].join("|")' 'true|100|true'
run_case dry_events_publish 'require "dry/events/publisher"; class RGoGateEvents; include Dry::Events::Publisher[:rgo_gate_events]; register_event("user.created"); end; events = RGoGateEvents.new; seen = []; events.subscribe("user.created", role: "admin") { |event| seen << [event.id, event[:name], event[:role]] }; events.publish("user.created", name: "Ada", role: "user"); events.publish("user.created", name: "Ruby", role: "admin"); puts [seen.length, *seen.first].join("|")' '1|user.created|Ruby|admin'
run_case dry_transaction_pipeline 'require "dry/transaction"; class RGoGateTransaction; include Dry::Transaction; include Dry::Monads[:result]; step :validate; step :double; private; def validate(input); input > 0 ? Success(input) : Failure(:invalid); end; def double(input); Success(input * 2); end; end; transaction = RGoGateTransaction.new; good = transaction.call(21); bad = transaction.call(-1); puts [good.success?, good.value!, bad.failure?, bad.failure].join("|")' 'true|42|true|invalid'
run_case fuubar_formatter 'require "stringio"; require "fuubar"; require "rspec/expectations"; output = StringIO.new; RSpec.configuration.fuubar_auto_refresh = false; RSpec.configuration.add_formatter(Fuubar, output); RSpec.describe("fuubar gate") { it("passes") { expect(6 * 7).to eq(42) } }; status = RSpec::Core::Runner.run([], $stderr, StringIO.new); text = output.string; puts [status, text.include?("1 example"), text.include?("0 failures"), text.length > 0].join("|")' '0|true|true|true'
run_case rspec_junit_formatter_xml 'require "stringio"; require "rspec_junit_formatter"; require "rspec/expectations"; output = StringIO.new; RSpec.configuration.add_formatter(RSpecJUnitFormatter, output); RSpec.describe("junit gate") { it("passes") { expect(21 * 2).to eq(42) } }; status = RSpec::Core::Runner.run([], $stderr, StringIO.new); xml = output.string; puts [status, xml.include?("testsuite"), xml.include?("junit gate"), xml.include?("failures=\"0\"")].join("|")' '0|true|true|true'
run_case rspec_junit_formatter_cli 'require "stringio"; require "rspec_junit_formatter"; require "rspec/expectations"; path = "/tmp/rgo-rspec-junit-cli-#{Process.pid}.xml"; RSpec.describe("junit cli gate") { it("passes") { expect(21 * 2).to eq(42) } }; status = RSpec::Core::Runner.run(["--format", "RspecJunitFormatter", "--out", path], $stderr, StringIO.new); xml = File.read(path); File.delete(path); puts [status, xml.include?("testsuite"), xml.include?("junit cli gate"), xml.include?("failures=\"0\"")].join("|")' '0|true|true|true'
run_case hana_json_patch 'require "hana"; patch = Hana::Patch.new([{"op" => "add", "path" => "/baz", "value" => "qux"}, {"op" => "replace", "path" => "/foo", "value" => "changed"}]); result = patch.apply({"foo" => "bar"}); puts [result["foo"], result["baz"], result.length].join("|")' 'changed|qux|2'
run_case simpleidn_roundtrip 'require "simpleidn"; ascii = SimpleIDN.to_ascii("møllerriis.com"); puts [ascii, SimpleIDN.to_unicode(ascii)].join("|")' 'xn--mllerriis-l8a.com|møllerriis.com'
run_case json_schemer_validation 'require "json_schemer"; schema = {"type" => "object", "properties" => {"name" => {"type" => "string", "minLength" => 1}, "age" => {"type" => "integer", "minimum" => 0}, "email" => {"type" => "string", "format" => "email"}}, "required" => ["name", "email"]}; schemer = JSONSchemer.schema(schema); valid = schemer.valid?({"name" => "John", "age" => 42, "email" => "john@example.com"}); invalid = {"name" => "", "age" => -1, "email" => "bad"}; errors = schemer.validate(invalid).to_a.map { |error| error["type"] }.sort; puts [valid, schemer.valid?(invalid), errors.length, errors.join(",")].join("|")' 'true|false|3|format,minLength,minimum'
run_case multi_json_roundtrip 'require "multi_json"; encoded = MultiJSON.generate({"answer" => 42}); parsed = MultiJSON.parse(encoded); symbols = MultiJson.load("{\"answer\":42}", symbolize_keys: true); begin; MultiJson.load("{bad}"); rescue MultiJSON::ParseError => error; puts [parsed["answer"], symbols[:answer], error.data, error.cause.class, error.cause.message.include?("invalid")].join("|"); end' '42|42|{bad}|JSON::ParserError|true'
run_case json_schema_validation 'require "json-schema"; schema = {"type" => "object", "required" => ["a"], "properties" => {"a" => {"type" => "integer", "minimum" => 2}}}; good = {"a" => 3}; bad = {"a" => "x"}; errors = JSON::Validator.fully_validate(schema, bad, errors_as_objects: true); raised = begin; JSON::Validator.validate!(schema, bad); false; rescue JSON::Schema::ValidationError; true; end; puts [JSON::Validator.validate(schema, good), JSON::Validator.validate(schema, bad), errors.length, errors.first[:failed_attribute], raised].join("|")' 'true|false|1|TypeV4|true'
run_case prometheus_client_metrics 'require "prometheus/client"; require "prometheus/client/formats/text"; registry = Prometheus::Client::Registry.new; counter = Prometheus::Client::Counter.new(:http_requests, docstring: "requests", labels: [:service]); histogram = Prometheus::Client::Histogram.new(:request_seconds, docstring: "latency", labels: [:service], buckets: [0.5, 1.0]); registry.register(counter); registry.register(histogram); counter.increment(by: 2, labels: {service: "api"}); counter.increment(by: 3, labels: {service: "api"}); histogram.observe(0.2, labels: {service: "api"}); histogram.observe(0.8, labels: {service: "api"}); text = Prometheus::Client::Formats::Text.marshal(registry); puts [counter.get(labels: {service: "api"}), text.include?("http_requests{service=\"api\"} 5"), text.include?("request_seconds_sum{service=\"api\"} 1"), text.include?("request_seconds_count{service=\"api\"} 2")].join("|")' '5.0|true|true|true'
run_case octokit_repository 'require "octokit"; named = Octokit::Repository.new("octokit/octokit.rb"); numbered = Octokit::Repository.new(42); invalid = begin; Octokit::Repository.new("bad/owner/repo"); false; rescue Octokit::InvalidRepository; true; end; puts [named.slug, named.path, numbered.path, invalid].join("|")' 'octokit/octokit.rb|repos/octokit/octokit.rb|repositories/42|true'
run_case faraday_multipart_request 'require "faraday"; require "faraday/multipart"; conn = Faraday.new do |builder|; builder.request :multipart; builder.adapter :test do |stub|; stub.post("/upload") do |env|; body = env.body.read; result = [env.request_headers["Content-Type"].start_with?("multipart/form-data; boundary="), body.include?("name=\"note\""), body.include?("hello-rgo"), env.request_headers["Content-Length"].to_i == body.bytesize]; [200, {"Content-Type" => "text/plain"}, result.join("|")]; end; end; end; part = Faraday::Multipart::ParamPart.new("hello-rgo", "text/plain"); puts conn.post("/upload", {note: part}).body' 'true|true|true|true'
run_case dry_system_container 'require "dry/system"; class RGoGateSystem < Dry::System::Container; end; calls = 0; RGoGateSystem.register("answer", memoize: true) { calls += 1; 42 }; first = RGoGateSystem["answer"]; second = RGoGateSystem["answer"]; missing = RGoGateSystem.resolve("missing") { |key| "fallback:#{key}" }; puts [first, second, calls, missing, RGoGateSystem.key?("answer")].join("|")' '42|42|1|fallback:missing|true'
run_case oauth2_authorize_url 'require "oauth2"; require "uri"; client = OAuth2::Client.new("client_id", "client_secret", site: "https://example.org/base", authorize_url: "/authorize", token_url: "/token"); uri = URI.parse(client.auth_code.authorize_url(redirect_uri: "https://app.test/cb", scope: "read write")); query = URI.decode_www_form(uri.query).to_h; puts [uri.scheme, uri.host, uri.path, query["client_id"], query["redirect_uri"], query["response_type"], query["scope"]].join("|")' 'https|example.org|/authorize|client_id|https://app.test/cb|code|read write'
run_case graphql_client_local_query 'require "graphql/client"; require "graphql"; class RGoClientGateQuery < GraphQL::Schema::Object; field :version, Integer, null: false; def version; 42; end; end; class RGoClientGateSchema < GraphQL::Schema; query(RGoClientGateQuery); end; module RGoClientGate; Client = GraphQL::Client.new(schema: RGoClientGateSchema, execute: RGoClientGateSchema); Query = Client.parse("query { version }"); end; result = RGoClientGate::Client.query(RGoClientGate::Query); puts [result.data.version, result.errors.empty?].join("|")' '42|true'
run_case net_ssh_config "require \"net/ssh\"; path = \"$tmp_dir/net_ssh_config\"; File.write(path, \"Host demo\\n  HostName example.test\\n  User alice\\n  Port 2222\\n  Compression yes\\n\"); options = Net::SSH::Config.for(\"demo\", [path]); puts [options[:host_name], options[:user], options[:port], options[:compression]].join(\"|\")" 'example.test|alice|2222|true'
run_case ast_node 'require "ast"; child = AST::Node.new(:int, [1]); node = AST::Node.new(:send, [nil, :value, child]); puts [node.type, node.children[1], node.children[2].type].join("|")' 'send|value|int'
run_case racc_runtime 'require "racc/parser.rb"; puts [Racc::VERSION, Racc::Parser.racc_runtime_type].join("|")' '1.8.1|ruby'
run_case parser_parse 'require "parser/current"; node = Parser::CurrentRuby.parse("answer = 1 + 2"); puts [Parser::VERSION, node.type, node.children[0], node.children[1].type].join("|")' '3.3.12.0|lvasgn|answer|send'
run_case rainbow_color 'require "rainbow"; require "rainbow/version"; Rainbow.enabled = true; puts [Rainbow::VERSION, Rainbow("ruby").red.include?("\e[31m")].join("|")' '3.1.1|true'
run_case regexp_parser_parse 'require "regexp_parser"; root = Regexp::Parser.parse("a+(?<name>b)"); puts [Regexp::Parser::VERSION, root.class.name, root.expressions.length].join("|")' '2.12.0|Regexp::Expression::Root|2'
run_case parallel_map 'require "parallel"; values = Parallel.map([1, 2, 3], in_threads: 1) { |value| value * 2 }; puts [Parallel::VERSION, values.join(",")].join("|")' '2.1.0|2,4,6'
run_case progressbar_state 'require "stringio"; require "ruby-progressbar"; require "ruby-progressbar/version"; output = StringIO.new; bar = ProgressBar.create(total: 2, output: output); 2.times { bar.increment }; puts [ProgressBar::VERSION, bar.finished?, bar.progress].join("|")' '1.13.0|true|2'
run_case unicode_width 'require "unicode/display_width"; puts [Unicode::DisplayWidth::VERSION, Unicode::DisplayWidth.of("A一"), Unicode::DisplayWidth.of("🤾🏽‍♀️", emoji: :all)].join("|")' '3.2.0|3|2'
run_case lsp_position 'require "language_server/protocol"; position = LanguageServer::Protocol::Interface::Position.new(line: 1, character: 2); puts [LanguageServer::Protocol::VERSION, position.to_hash[:line], position.to_hash[:character]].join("|")' '3.17.0.6|1|2'
run_case docile_dsl_eval 'require "docile"; target = []; outer = "outer"; result = Docile.dsl_eval(target) { push(outer); push("dsl") }; puts [Docile::VERSION, target.join(","), result].join("|")' '1.4.1|outer,dsl|outer|dsl'
run_case simplecov_start 'require "simplecov"; SimpleCov.at_exit {}; SimpleCov.start; puts [SimpleCov::VERSION, Coverage.running?].join("|")' '1.0.3|true'
run_case reline_history_keystroke 'require "reline"; config = Reline::Config.new; config.history_size = 2; history = Reline::History.new(config); history << "one" << "two" << "three"; stroke = Reline::KeyStroke.new(config, Encoding::UTF_8); status = stroke.match_status("a".bytes); keys, rest = stroke.expand("a".bytes); puts [Reline::VERSION, history.join(","), history[-1], status, keys.first.char, keys.first.method_symbol, rest.empty?].join("|")' '0.6.3|two,three|three|matched|a|ed_insert|true'
run_case base64_binary_roundtrip 'require "base64"; raw = "ruby\x00go"; encoded = Base64.strict_encode64(raw); puts [encoded, Base64.strict_decode64(encoded) == raw].join("|")' 'cnVieQBnbw==|true'
run_case bcrypt_password 'require "bcrypt"; password = BCrypt::Password.create("secret", cost: 4); reference = BCrypt::Password.new("$2a$10$XajjQvNhvvRt5GSeFk1xFeyqRrsxkhBkUiQeg0dt.wU1qD4aFDcga"); invalid = begin; BCrypt::Password.new("bad"); rescue BCrypt::Errors::InvalidHash; true; end; puts [Gem.loaded_specs["bcrypt"].version, password.to_s.length, password.cost, password == "secret", password == "wrong", reference == "allmine", reference == "wrong", invalid].join("|")' '3.1.22|60|4|true|false|true|false|true'
run_case devise_encryptor 'require "devise"; require "devise/version"; class RGoGateDeviseConfig; def self.pepper; "pepper"; end; def self.stretches; 4; end; end; digest = Devise::Encryptor.digest(RGoGateDeviseConfig, "secret"); puts [Devise::VERSION, digest.length, Devise::Encryptor.compare(RGoGateDeviseConfig, digest, "secret"), Devise::Encryptor.compare(RGoGateDeviseConfig, digest, "wrong"), Devise.secure_compare("same", "same"), Devise.secure_compare("same", "diff")].join("|")' '5.0.4|60|true|false|true|false'
run_case benchmark_ips_sample 'require "benchmark/ips"; report = Benchmark.ips(time: 0.05, warmup: 0, quiet: true) { |x| x.report("add") { 20 + 22 } }; entry = report.entries.first; puts [entry.label, entry.iterations > 0, entry.ips > 0].join("|")' 'add|true|true'
run_case sorbet_runtime_sig 'require "sorbet-runtime"; class RGoGateTypedCalculator; extend T::Sig; sig { params(x: Integer).returns(Integer) }; def twice(x); x * 2; end; end; bad = begin; RGoGateTypedCalculator.new.twice("x"); rescue => error; error.class; end; puts [RGoGateTypedCalculator.new.twice(21), bad].join("|")' '42|TypeError'
run_case fiber_storage_inheritance 'require "fiber/storage"; Fiber[:request_id] = 42; values = Fiber.new { [Fiber[:request_id], Fiber.current.storage[:request_id]] }.resume; puts values.join("|")' '42|42'
run_case graphql_execute 'require "graphql"; class RGoGemGateQuery < GraphQL::Schema::Object; field :greeting, String, null: false; def greeting; "hello graphql"; end; end; class RGoGemGateSchema < GraphQL::Schema; query(RGoGemGateQuery); end; result = RGoGemGateSchema.execute("{ greeting }").to_h; puts [GraphQL::VERSION, result["data"]["greeting"]].join("|")' '2.6.7|hello graphql'
run_case sidekiq_normalize_job 'require "sidekiq"; item = Object.new.extend(Sidekiq::JobUtil).normalize_item({"class" => "DemoJob", "args" => [24], "queue" => :critical}); puts [Sidekiq::VERSION, item["class"], item["queue"], item["args"].first, item["jid"].length == 24].join("|")' '7.3.10|DemoJob|critical|24|true'
run_case faker_name_email 'require "faker"; Faker::Config.random = Random.new(42); name = Faker::Name.name; email = Faker::Internet.email(name: name); puts [Faker::VERSION, !name.empty?, email.include?("@")].join("|")' '3.8.0|true|true'
run_case cancancan_conditions 'require "cancan"; class RGoGemGateArticle; attr_reader :published, :user_id; def initialize(published, user_id); @published = published; @user_id = user_id; end; end; class RGoGemGateAbility; include CanCan::Ability; def initialize(uid); can :read, RGoGemGateArticle, published: true; can :update, RGoGemGateArticle, user_id: uid; end; end; ability = RGoGemGateAbility.new(7); good = RGoGemGateArticle.new(true, 7); bad = RGoGemGateArticle.new(false, 8); puts [CanCan::VERSION, ability.can?(:read, good), ability.cannot?(:read, bad), ability.can?(:update, good), ability.cannot?(:update, bad)].join("|")' '3.6.1|true|true|true|true'
run_case pagy_offset 'require "pagy"; page = Pagy::Offset.new(count: 95, page: 3, limit: 20); puts [Pagy::VERSION, page.page, page.limit, page.offset, page.pages].join("|")' '43.6.1|3|20|40|5'
run_case bigdecimal_arithmetic 'require "bigdecimal"; total = BigDecimal("12.50") + BigDecimal("0.75"); puts [BigDecimal::VERSION, total.to_s("F")].join("|")' '3.3.1|13.25'
run_case factory_bot_build 'require "factory_bot"; class GateFactoryUser; attr_accessor :name, :age; end; FactoryBot.define { factory :gate_factory_user do; name { "Ada" }; age { 37 }; end }; user = FactoryBot.build(:gate_factory_user); puts [FactoryBot::VERSION, user.class.name, user.name, user.age].join("|")' '6.6.0|GateFactoryUser|Ada|37'
run_case crack_json_xml 'require "crack"; json = Crack::JSON.parse(%q({"user":{"name":"Ada"}})); xml = Crack::XML.parse("<user><name>Ada</name></user>"); puts [Crack::VERSION, json["user"]["name"], xml["user"]["name"]].join("|")' '1.0.1|Ada|Ada'
run_case hashdiff_nested 'require "hashdiff"; diff = Hashdiff.diff({"user" => {"name" => "Ada", "age" => 36}}, {"user" => {"name" => "Ada", "age" => 37}, "active" => true}); puts [Hashdiff::VERSION, diff.length, diff[0][0], diff[0][1], diff[1][0]].join("|")' '1.2.1|2|~|user.age|+'
run_case blueprinter_render 'require "blueprinter"; require "blueprinter/version"; class GateBlueprintUser; attr_reader :id, :name; def initialize(id, name); @id = id; @name = name; end; end; class GateUserBlueprint < Blueprinter::Base; identifier :id; fields :name; end; puts [Blueprinter::VERSION, GateUserBlueprint.render(GateBlueprintUser.new(7, "Ada"))].join("|")' '1.3.0|{"id":7,"name":"Ada"}'
run_case kaminari_page_per 'require "kaminari/core"; require "kaminari/core/version"; values = Kaminari.paginate_array((1..10).to_a).page(2).per(3); puts [Kaminari::Core::VERSION, values.to_a.join(","), values.first, values.total_count].join("|")' '1.2.2|4,5,6|4|10'
run_case omniauth_callback 'require "omniauth"; require "omniauth/version"; require "rack/mock"; OmniAuth.config.logger.level = Logger::FATAL; class GateOmniAuthStrategy; include OmniAuth::Strategy; option :name, "gate"; uid { "42" }; info { {name: "Ada"} }; end; app = Rack::Builder.new do; use GateOmniAuthStrategy; run ->(env) { auth = env["omniauth.auth"]; body = auth ? [auth.provider, auth.uid, auth.info.name].join("|") : "fallback"; [200, {"content-type" => "text/plain"}, [body]] }; end.to_app; response = Rack::MockRequest.new(app).get("/auth/gate/callback", "rack.session" => {}); puts [OmniAuth::VERSION, response.status, response.body].join("|")' '2.1.4|200|gate|42|Ada'
run_case warden_password_strategy 'require "rack"; require "warden"; Warden::Strategies.add(:rgo_gate_password) do; def valid?; params["name"] && params["password"]; end; def authenticate!; params["password"] == "secret" ? success!({name: params["name"]}) : fail!("bad password"); end; end; endpoint = ->(env) { user = env["warden"].authenticate!(:rgo_gate_password); [200, {"content-type" => "text/plain"}, [user[:name]]] }; manager = Warden::Manager.new(endpoint) do |config|; config.failure_app = ->(env) { [401, {"content-type" => "text/plain"}, [env["warden.options"][:message]]] }; end; app = ->(env) { env["rack.session"] = {}; manager.call(env) }; request = Rack::MockRequest.new(app); good = request.get("/?name=ruby&password=secret"); bad = request.get("/?name=ruby&password=no"); puts [good.status, good.body, bad.status, bad.body].join("|")' '200|ruby|401|bad password'
run_case orm_adapter_active_record 'require "active_record"; require "orm_adapter"; require "orm_adapter/adapters/active_record"; class RGoGateOrmRelation; attr_reader :steps; def initialize; @steps = []; end; def where(value); @steps << [:where, value]; self; end; def order(value); @steps << [:order, value]; self; end; def limit(value); @steps << [:limit, value]; self; end; def offset(value); @steps << [:offset, value]; self; end; end; class RGoGateOrmUser < ActiveRecord::Base; self.abstract_class = true; def self.column_names; %w[id name age]; end; def self.where(value); RGoGateOrmRelation.new.where(value); end; end; adapter = RGoGateOrmUser.to_adapter; relation = adapter.find_all(conditions: {name: "Ruby"}, order: [:age, :desc], limit: 2, offset: 1); puts [adapter.class.name, adapter.column_names.join(","), relation.steps.inspect].join("|")' 'OrmAdapter::ActiveRecord|id,name,age|[[:where, {name: "Ruby"}], [:order, "age desc"], [:limit, 2], [:offset, 1]]'
run_case webmock_net_http_stub 'require "webmock"; require "webmock/version"; require "net/http"; include WebMock::API; WebMock.enable!; stub_request(:get, "http://example.test/hello").to_return(status: 200, body: "stubbed"); response = Net::HTTP.get_response(URI("http://example.test/hello")); puts [WebMock::VERSION, response.code, response.body].join("|")' '3.26.2|200|stubbed'
run_case excon_stub 'require "excon"; Excon.stub({method: :get, path: "/hello"}, {status: 200, body: "stubbed"}); response = Excon.get("http://example.test/hello", mock: true); puts [Excon::VERSION, response.status, response.body].join("|")' '1.6.0|200|stubbed'
run_case redis_namespace_set_get 'require "redis-namespace"; class RGoGemGateRedisNamespaceBackend; def initialize; @data = {}; end; def set(key, value, *); @data[key] = value; "OK"; end; def get(key); @data[key]; end; def id; "fake"; end; end; redis = RGoGemGateRedisNamespaceBackend.new; namespaced = Redis::Namespace.new(:gate, redis: redis, warning: false); namespaced.set("key", "value"); puts [Redis::Namespace::VERSION, namespaced.get("key"), redis.get("gate:key")].join("|")' '1.11.0|value|value'
run_case semantic_logger_json 'require "semantic_logger"; require "stringio"; require "json"; io = StringIO.new; SemanticLogger.add_appender(io: io, formatter: :json); logger = SemanticLogger["Gate"]; logger.info("hello", {id: 42}); SemanticLogger.flush; parsed = JSON.parse(io.string.lines.last); puts [SemanticLogger::VERSION, parsed["name"], parsed["message"], parsed["payload"]["id"]].join("|")' '5.1.0|Gate|hello|42'
run_case sprockets_default_asset "require \"sprockets\"; path = \"$tmp_dir/rgo_sprockets_asset.js\"; File.write(path, \"const rgoSprocketsGate = 42;\\n\"); env = Sprockets::Environment.new; env.append_path(\"$tmp_dir\"); asset = env.find_asset(\"rgo_sprockets_asset.js\"); puts [Sprockets::VERSION, asset.logical_path, asset.length, asset.to_s.include?(\"rgoSprocketsGate = 42\")].join(\"|\")" '4.2.2|rgo_sprockets_asset.js|30|true'
run_case aws_sigv4_jmespath 'require "aws-sdk-core"; require "aws-sigv4"; require "jmespath"; credentials = Aws::Credentials.new("AKID", "SECRET"); signer = Aws::Sigv4::Signer.new(service: "s3", region: "us-east-1", access_key_id: "AKID", secret_access_key: "SECRET"); signature = signer.sign_request(http_method: "GET", url: "https://s3.us-east-1.amazonaws.com/example", headers: {}, body: ""); query = JMESPath.search("users[?active].name | [0]", {"users" => [{"name" => "Ada", "active" => true}, {"name" => "Bob", "active" => false}]}); puts [Aws::CORE_GEM_VERSION, credentials.set?, signature.headers["authorization"].include?("AWS4-HMAC-SHA256"), query].join("|")' '3.254.0|true|true|Ada'
run_case dotenv_parse "require \"dotenv\"; path = \"$tmp_dir/functional.env\"; File.write(path, \"RGO_GEM_NAME=dotenv\\nRGO_GEM_COUNT=2\\n\"); values = Dotenv.parse(path); puts [values[\"RGO_GEM_NAME\"], values[\"RGO_GEM_COUNT\"]].join(\"|\")" 'dotenv|2'
run_case httparty_json_parser 'require "httparty"; value = HTTParty::Parser.call(%q({"ok":true,"items":[1,2]}), :json); puts [value["ok"], value["items"].last].join("|")' 'true|2'
run_case mini_mime_lookup 'require "mini_mime"; info = MiniMime.lookup_by_filename("report.json"); puts [info.content_type, info.extension].join("|")' 'application/json|json'
run_case mail_encode_parse 'require "mail"; mail = Mail.new; mail.from = "ada@example.com"; mail.to = "ruby@example.com"; mail.subject = "Hello"; mail.body = "RGo body"; parsed = Mail.read_from_string(mail.encoded); puts [Mail::VERSION::STRING, parsed.from.first, parsed.to.first, parsed.subject, parsed.body.decoded].join("|")' '2.9.1|ada@example.com|ruby@example.com|Hello|RGo body'
run_case marcel_mime_detection 'require "marcel"; require "stringio"; png = "\x89PNG\r\n\x1a\n"; puts [Marcel::VERSION, Marcel::MimeType.for(StringIO.new(png), name: "image.png"), Marcel::MimeType.for(name: "report.pdf")].join("|")' '1.2.1|image/png|application/pdf'
run_case net_imap_response_parser 'require "net/imap"; response = Net::IMAP::ResponseParser.new.parse("* 2 EXISTS\r\n"); puts [Net::IMAP::VERSION, response.name, response.data].join("|")' '0.6.6|EXISTS|2'
run_case globalid_locator 'require "globalid"; GlobalID.app = "rgo"; class RGoGemGateGlobalPerson; include GlobalID::Identification; attr_reader :id; def initialize(id); @id = id; end; def self.find(id); new(id); end; end; gid = RGoGemGateGlobalPerson.new(42).to_global_id; located = GlobalID::Locator.locate(gid); puts [GlobalID::VERSION, gid.to_s, located.class.name, located.id].join("|")' '1.4.0|gid://rgo/RGoGemGateGlobalPerson/42|RGoGemGateGlobalPerson|42'
run_case active_model_validation 'require "active_model"; class Person; include ActiveModel::Model; attr_accessor :name, :age; validates :name, presence: true; validates :age, numericality: {greater_than_or_equal_to: 18}; end; good = Person.new(name: "Ada", age: 37); bad = Person.new(name: "", age: 17); puts [good.valid?, Person.model_name.singular, bad.valid?, bad.errors[:name].first, bad.errors[:age].first].join("|")' 'true|person|false|can'\''t be blank|must be greater than or equal to 18'
run_case active_record_types_arel 'require "active_record"; integer = ActiveRecord::Type::Integer.new; boolean = ActiveRecord::Type::Boolean.new; table = Arel::Table.new(:users); predicate = table[:age].gteq(18).and(table[:active].eq(true)); puts [integer.cast("42"), boolean.cast("0"), predicate.class.name].join("|")' '42|false|Arel::Nodes::And'
run_case active_job_inline 'require "active_job"; ActiveJob::Base.logger = nil; ActiveJob::Base.queue_adapter = :inline; class RGoGemGateInlineJob < ActiveJob::Base; RESULTS = []; def perform(value, add:); RESULTS << value + add; end; end; job = RGoGemGateInlineJob.perform_later(40, add: 2); puts [ActiveJob.version, job.successfully_enqueued?, RGoGemGateInlineJob::RESULTS.last].join("|")' '8.1.2|true|42'
run_case faraday_retry_status 'require "faraday"; require "faraday/retry"; attempts = 0; conn = Faraday.new do |builder|; builder.request :retry, max: 1, interval: 0, retry_statuses: [503]; builder.adapter :test do |stub|; stub.get("/retry") { attempts += 1; attempts == 1 ? [503, {}, "wait"] : [200, {}, "ok"] }; end; end; response = conn.get("/retry"); puts [Faraday::Retry::VERSION, response.status, response.body, attempts].join("|")' '2.4.0|200|ok|2'
run_case rack_attack_throttle 'require "active_support"; require "active_support/isolated_execution_state"; require "active_support/notifications"; require "active_support/cache"; require "rack/attack"; require "rack/mock"; Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new; Rack::Attack.throttle("requests/ip", limit: 1, period: 60) { |request| request.ip }; app = Rack::Attack.new(->(_env) { [200, {"content-type" => "text/plain"}, ["ok"]] }); first = Rack::MockRequest.new(app).get("/", "REMOTE_ADDR" => "192.0.2.1"); second = Rack::MockRequest.new(app).get("/", "REMOTE_ADDR" => "192.0.2.1"); puts [first.status, second.status].join("|")' '200|429'
run_case request_store_middleware 'require "request_store"; require "rack/mock"; app = RequestStore::Middleware.new(->(_env) { RequestStore.store[:count] = RequestStore.store.fetch(:count, 0) + 1; [200, {"content-type" => "text/plain"}, [RequestStore.store[:count].to_s]] }); request = Rack::MockRequest.new(app); puts [request.get("/").body, request.get("/").body].join("|")' '1|1'
run_case liquid_render 'require "liquid"; template = Liquid::Template.parse("{% for item in items %}{{ item | upcase }}{% unless forloop.last %},{% endunless %}{% endfor %}"); puts [Liquid::VERSION, template.render("items" => ["ruby", "go"])].join("|")' '5.13.0|RUBY,GO'
run_case slim_render 'require "slim"; template = Slim::Template.new { "h1 Hello\np = name" }; puts [Slim::VERSION, template.render(Object.new, name: "Ada").delete("\n")].join("|")' '5.2.2|<h1>Hello</h1><p>Ada</p>'
run_case haml_render 'require "haml"; template = Haml::Template.new { "%h1 Hello\n%p= name" }; puts [Haml::VERSION, template.render(Object.new, name: "Ada").delete("\n")].join("|")' '7.2.2|<h1>Hello</h1><p>Ada</p>'
run_case erubi_render 'require "erubi"; name = "Ada"; source = Erubi::Engine.new("<h1><%= name %></h1>").src; puts [Erubi::VERSION, eval(source, binding)].join("|")' '1.13.1|<h1>Ada</h1>'
run_case jbuilder_render 'require "jbuilder"; json = Jbuilder.new; json.user do; json.name "Ada"; json.roles ["admin", "author"]; end; puts [Jbuilder::VERSION, json.target!].join("|")' '2.15.1|{"user":{"name":"Ada","roles":["admin","author"]}}'
run_case enumerize_predicates 'require "enumerize"; class RGoGateEnumUser; extend Enumerize; enumerize :role, in: [:user, :admin], default: :user, predicates: true; end; user = RGoGateEnumUser.new; before = [user.role.to_s, user.user?, user.admin?]; user.role = :admin; puts [*before, user.role.to_s, user.admin?, RGoGateEnumUser.role.values.map(&:to_s).join(",")].join("|")' 'user|true|false|admin|true|user,admin'
run_case dry_struct_attributes 'require "dry-struct"; module RGoGateTypes; include Dry.Types(); end; class RGoGateBook < Dry::Struct; attribute :title, RGoGateTypes::String; attribute :pages, RGoGateTypes::Integer; end; book = RGoGateBook.new(title: "Ruby", pages: 320); missing = begin; RGoGateBook.new(title: "Ruby"); rescue Dry::Struct::Error; :error; end; puts [book.title, book.pages, missing, book.to_h].inspect' '["Ruby", 320, :error, {title: "Ruby", pages: 320}]'
run_case audited_model_config 'require "active_record"; module Rails; module VERSION; STRING = "8.1.2"; end; def self.gem_version; Gem::Version.new(VERSION::STRING); end; class Railtie; def self.initializer(*args); end; end; end; require "audited"; class RGoGateAuditedModel < ActiveRecord::Base; self.abstract_class = true; attribute :title, ActiveRecord::Type::String.new; attribute :secret, ActiveRecord::Type::String.new; def self.columns; []; end; def self.column_names; %w[id title secret created_at updated_at]; end; audited only: [:title], on: [:update]; end; puts [RGoGateAuditedModel.included_modules.include?(Audited::Auditor::AuditedInstanceMethods), RGoGateAuditedModel.audited_options[:on].join(","), RGoGateAuditedModel.audited_options[:only].join(","), RGoGateAuditedModel._update_callbacks.map(&:filter).include?(:audit_update)].join("|")' 'true|update|title|true'
run_case state_machines_transition 'require "state_machines"; class RGoGateVehicle; state_machine :state, initial: :parked do; event :ignite do; transition parked: :idling; end; event :park do; transition idling: :parked; end; end; end; vehicle = RGoGateVehicle.new; before = [vehicle.state, vehicle.parked?, vehicle.can_ignite?]; first = vehicle.ignite; middle = [vehicle.state, vehicle.idling?, vehicle.can_park?]; second = vehicle.park; puts [*before, first, *middle, second, vehicle.state].join("|")' 'parked|true|true|true|idling|true|true|true|parked'
run_case active_record_ecosystem 'require "active_record"; require "ransack"; require "friendly_id"; require "discard"; require "paper_trail"; require "counter_culture"; RGoGateColumn = Struct.new(:name, :type); class RGoGateSchemaCache; def data_source_exists?(_name); true; end; def primary_keys(_name); "id"; end; end; class RGoGateConnection; def table_alias_length; 64; end; def schema_cache; @schema_cache ||= RGoGateSchemaCache.new; end; end; class RGoGatePool; def initialize; @connection = RGoGateConnection.new; end; def with_connection; yield @connection; end; def permanent_lease?; true; end; def lease_connection; @connection; end; def schema_cache; @connection.schema_cache; end; end; class RGoGateRecord < ActiveRecord::Base; self.abstract_class = true; self.primary_key = "id"; def self.columns_hash; {}; end; def self.connection_pool; @rgo_gate_pool ||= RGoGatePool.new; end; def self.with_connection; connection_pool.with_connection { |connection| yield connection }; end; def self.table_exists?; true; end; end; class RGoGateSearch < RGoGateRecord; attribute :name, ActiveRecord::Type::String.new; attribute :price, ActiveRecord::Type::Integer.new; def self.columns; [RGoGateColumn.new("name", :string), RGoGateColumn.new("price", :integer)]; end; def self.ransackable_attributes(_auth = nil); %w[name price]; end; def self.ransackable_associations(_auth = nil); []; end; end; search = RGoGateSearch.ransack(name_cont: "ruby", price_gteq: 10); class RGoGateFriendly < RGoGateRecord; extend FriendlyId; attribute :name, ActiveRecord::Type::String.new; attribute :slug, ActiveRecord::Type::String.new; friendly_id :name, use: :slugged; end; friendly = RGoGateFriendly.new(name: "Hello Ruby World"); class RGoGateDiscard < RGoGateRecord; include Discard::Model; attribute :discarded_at, ActiveRecord::Type::DateTime.new; end; discarded = RGoGateDiscard.new; discard_before = [discarded.kept?, discarded.discarded?]; discarded.discarded_at = Time.utc(2026, 7, 30); discard_after = [discarded.kept?, discarded.discarded?]; discard_nodes = [RGoGateDiscard.kept, RGoGateDiscard.discarded].map { |relation| relation.where_clause.send(:predicates).first.class.name }; class RGoGateAudited < RGoGateRecord; attribute :title, ActiveRecord::Type::String.new; has_paper_trail on: [:update]; end; audited = RGoGateAudited.new(title: "Draft"); paper_inside = PaperTrail.request(enabled: false) { PaperTrail.request.enabled? }; paper_proc_callbacks = RGoGateAudited._update_callbacks.count { |callback| callback.kind == :after && callback.filter.is_a?(Proc) }; class RGoGateCounted < RGoGateRecord; attribute :category_id, ActiveRecord::Type::Integer.new; belongs_to :category, class_name: "RGoGateCategory"; counter_culture :category, column_name: "posts_count"; end; counter = RGoGateCounted.after_commit_counter_cache.first; puts [search.conditions.length, search.conditions.map { |condition| condition.predicate.name }.join(","), friendly.normalize_friendly_id(friendly.name), friendly.should_generate_new_friendly_id?, *discard_before, *discard_after, *discard_nodes, paper_inside, PaperTrail.request.enabled?, audited.paper_trail.class.name, RGoGateAudited.paper_trail_options[:on].join(","), paper_proc_callbacks, RGoGateCounted.after_commit_counter_cache.length, counter.relation, counter.counter_cache_name, RGoGateCounted._create_callbacks.map(&:filter).include?(:_update_counts_after_create)].join("|")' '2|cont,gteq|hello-ruby-world|true|true|false|false|true|Arel::Nodes::Equality|Arel::Nodes::NotEqual|false|true|PaperTrail::RecordTrail|update|2|1|category|posts_count|true'
run_case multi_xml_rexml 'require "multi_xml"; require "multi_xml/version"; data = MultiXml.parse("<person><name>Ada</name><age>37</age></person>", parser: :rexml); puts [MultiXml::VERSION, data["person"]["name"], data["person"]["age"]].join("|")' '0.9.1|Ada|37'
run_case minitest_assertion 'require "minitest"; klass = Class.new { include Minitest::Assertions; attr_accessor :assertions; def initialize; @assertions = 0; end }; probe = klass.new; probe.assert_equal(42, 40 + 2); puts probe.assertions' '1'
run_case minitest_test_case 'require "minitest"; klass = Class.new(Minitest::Test) { def test_ok; assert_equal 42, 40 + 2; end }; result = klass.new(:test_ok).run; puts [result.passed?, result.assertions, result.failures.length].join(":")' 'true:1:0'
run_case minitest_spec 'require "minitest/spec"; klass = describe("math") { it("adds") { _(1 + 1).must_equal 2 } }; result = klass.new("test_0001_adds").run; puts [result.passed?, result.assertions, result.failures.length].join(":")' 'true:1:0'
run_case public_suffix_domain 'require "public_suffix"; domain = PublicSuffix.parse("www.example.co.uk"); puts [domain.tld, domain.sld, domain.trd, domain.domain].join(":")' 'co.uk:example:www:example.co.uk'
run_case addressable_uri 'require "addressable/uri"; uri = Addressable::URI.parse("HTTP://Example.COM/a b?x=1&tag=ruby").normalize; values = uri.query_values; puts [uri.to_s, values["x"], values["tag"]].join(":")' 'http://example.com/a%20b?x=1&tag=ruby:1:ruby'
run_case addressable_template 'require "addressable/template"; template = Addressable::Template.new("https://example.com{/segments*}{?q,limit}"); uri = template.expand(segments: ["api", "v1"], q: "ruby go", limit: 10); puts [template.variables.join(","), uri.to_s].join(":")' 'segments,q,limit:https://example.com/api/v1?q=ruby%20go&limit=10'
run_case i18n_translate 'require "i18n"; I18n.available_locales = [:en]; I18n.backend.store_translations(:en, hello: "world"); puts I18n.t(:hello, locale: :en)' 'world'
run_case i18n_interpolate_plural 'require "i18n"; I18n.available_locales = [:en]; I18n.backend.store_translations(:en, {greeting: "Hello %{name}", apples: {one: "%{count} apple", other: "%{count} apples"}}); puts [I18n.t(:greeting, name: "Ruby", locale: :en), I18n.t(:apples, count: 2, locale: :en)].join(":")' 'Hello Ruby:2 apples'
run_case i18n_fallback 'require "i18n"; require "i18n/backend/fallbacks"; I18n::Backend::Simple.include(I18n::Backend::Fallbacks); I18n.available_locales = [:en, :"en-GB"]; I18n.backend.store_translations(:en, {hello: "world"}); puts I18n.t(:hello, locale: :"en-GB")' 'world'
run_case i18n_default 'require "i18n"; I18n.available_locales = [:en]; puts I18n.t(:missing, locale: :en, default: "fallback")' 'fallback'
run_case concurrent_map 'require "concurrent/map"; map = Concurrent::Map.new; map[:answer] = 42; puts map.fetch(:answer)' '42'
run_case concurrent_atomic 'require "concurrent"; counter = Concurrent::AtomicFixnum.new(0); 10_000.times { counter.increment }; puts counter.value' '10000'
run_case concurrent_promise_immediate 'require "concurrent"; promise = Concurrent::Promise.execute(executor: Concurrent::ImmediateExecutor.new) { 21 }.then { |value| value * 2 }; puts promise.value!' '42'
run_case concurrent_promise_default 'require "concurrent"; promise = Concurrent::Promise.execute { 21 }.then { |value| value * 2 }; puts promise.value!(1)' '42'
run_case connection_pool_checkout 'require "connection_pool"; pool = ConnectionPool.new(size: 2, timeout: 1) { Object.new }; resource = nil; pool.with { |value| resource = value }; reused = pool.with { |value| value.equal?(resource) }; puts [reused, pool.available].join(":")' 'true:2'
run_case erb_result_with_hash 'require "erb"; locals = {name: "Ruby", "count" => 2}; puts ERB.new("Hello <%= name %>, <%= count %>!").result_with_hash(locals)' 'Hello Ruby, 2!'
run_case thor_cli 'require "thor"; class RGoGemGateCLI < Thor; desc "hello NAME", "greets a name"; option :upcase, type: :boolean; def hello(name); text = "Hello #{name}"; puts(options[:upcase] ? text.upcase : text); end; end; RGoGemGateCLI.start(["hello", "Ruby", "--upcase"])' 'HELLO RUBY'
run_case tzinfo_utc 'require "tzinfo"; zone = TZInfo::Timezone.get("UTC"); local = zone.to_local(Time.utc(2024, 1, 2, 3, 4, 5)); puts [zone.identifier, local.year, local.hour].join(":")' 'UTC:2024:3'
run_case rake_task_registry 'require "rake"; Rake::Task.define_task(:hello); puts Rake::Task.tasks.map(&:name).join(",")' 'hello'
run_case rake_task_invoke 'require "rake"; values = []; Rake::Task.define_task(:hello) { values << :ok }; Rake::Task[:hello].invoke; puts values.join(",")' 'ok'
run_case rake_task_dependencies 'require "rake"; values = []; task(:prepare) { values << :prepare }; task(build: :prepare) { values << :build }; Rake::Task[:build].invoke; puts values.join(",")' 'prepare,build'
run_case zeitwerk_autoload "require \"zeitwerk\"; loader = Zeitwerk::Loader.new; loader.push_dir(\"$project_root/testdata/gems/zeitwerk_fixture\"); loader.setup; autoloaded = DemoWidget.value; loader.eager_load; puts [autoloaded, EagerThing.value].join(\":\")" '42:7'
run_case zeitwerk_reload "require \"zeitwerk\"; loader = Zeitwerk::Loader.new; loader.enable_reloading; loader.push_dir(\"$project_root/testdata/gems/zeitwerk_fixture\"); loader.setup; first = DemoWidget.value; loader.reload; puts [first, DemoWidget.value].join(\":\")" '42:42'
run_case active_support_core_ext 'require "active_support/core_ext/array/access"; require "active_support/core_ext/hash/except"; puts [[1, 2, 3, 4].second_to_last, {a: 1, b: 2}.except(:a)[:b]].join(":")' '3:2'
run_case active_support_inflections 'require "active_support/core_ext/string/inflections"; puts ["active_model".camelize, "ActiveModel".underscore, "posts".singularize].join(":")' 'ActiveModel:active_model:post'
run_case active_support_json 'require "active_support/json"; escaped = ActiveSupport::JSON.encode({a: 1, text: "<ruby>"}); raw = ActiveSupport::JSON.encode({text: "<ruby>"}, escape: false); puts [escaped, raw].join(":")' '{"a":1,"text":"\u003cruby\u003e"}:{"text":"<ruby>"}'
run_case faraday_test_adapter 'require "faraday"; conn = Faraday.new { |builder| builder.adapter :test do |stub| stub.get("/ebi") { [200, {"Content-Type" => "text/plain"}, "shrimp"] }; end }; response = conn.get("/ebi"); puts [response.status, response.body, response.headers["content-type"]].join("|")' '200|shrimp|text/plain'
run_case faraday_json 'require "faraday"; conn = Faraday.new { |builder| builder.request :json; builder.response :json; builder.adapter :test do |stub| stub.post("/echo") { |env| [200, {"Content-Type" => "application/json"}, env.body] }; end }; response = conn.post("/echo", {foo: "bar"}); puts [response.status, response.body["foo"], response.env.request_headers["Content-Type"]].join("|")' '200|bar|application/json'
run_case logger_filter "require \"logger\"; path = \"$tmp_dir/logger.log\"; logger = Logger.new(path); logger.level = Logger::INFO; logger.debug(\"hidden\"); logger.info(\"visible\"); logger.close; contents = File.read(path); puts [logger.level, contents.include?(\"visible\"), !contents.include?(\"hidden\")].join(\":\")" '1:true:true'
run_case dry_core_class_attributes 'require "dry/core"; class RGoDryBase; extend Dry::Core::ClassAttributes; defines :one, :two, type: Integer; one 1; two 2; end; class RGoDryChild < RGoDryBase; two 3; end; invalid = begin; RGoDryChild.one "bad"; false; rescue Dry::Core::InvalidClassAttributeValueError; true; end; puts [RGoDryBase.one, RGoDryChild.one, RGoDryChild.two, invalid].join(":")' '1:1:3:true'
run_case dry_core_cache 'require "dry/core"; class RGoDryCached; extend Dry::Core::Cache; attr_reader :calls; def initialize; @calls = 0; end; def compute(a, b); fetch_or_store(a, b) { @calls += 1; a + b }; end; end; cached = RGoDryCached.new; puts [cached.compute(20, 22), cached.compute(20, 22), cached.calls].join(":")' '42:42:1'
run_case dry_core_extensions 'require "dry/core"; class RGoDryExtensible; extend Dry::Core::Extensions; register_extension(:bar) { def bar; :bar; end }; end; before = RGoDryExtensible.new.respond_to?(:bar); RGoDryExtensible.load_extensions(:bar); puts [before, RGoDryExtensible.new.bar].join(":")' 'false:bar'
run_case dry_core_container 'require "dry/core"; container = Dry::Core::Container.new; container.register(:plain, "value"); calls = 0; container.register(:factory, -> { calls += 1; "made" }); container.register(:memo, -> { Object.new }, memoize: true); first = container.resolve(:memo); puts [container.resolve(:plain), container.resolve(:factory), calls, first.equal?(container.resolve(:memo)), container.key?(:plain)].join(":")' 'value:made:1:true:true'
run_case dry_configurable_settings 'require "dry/configurable"; class RGoConfigSettings; extend Dry::Configurable; setting :environment, default: "development"; setting :log_level, default: :info, constructor: ->(value) { value.to_sym }; setting :secret_key, default: nil, reader: true; setting :mailer do; setting :host, default: "smtp.example.com"; setting :port, default: 587; end; end; RGoConfigSettings.config.log_level = "warn"; RGoConfigSettings.config.mailer.port = 465; puts [RGoConfigSettings.config.environment, RGoConfigSettings.config.log_level, RGoConfigSettings.secret_key.nil?, RGoConfigSettings.config.mailer.host, RGoConfigSettings.config.mailer.port].join(":")' 'development:warn:true:smtp.example.com:465'
run_case dry_configurable_inheritance 'require "dry/configurable"; class RGoConfigBase; extend Dry::Configurable; setting :log_level, default: :info; setting :database do; setting :pool, default: 5; end; end; class RGoConfigProduction < RGoConfigBase; setting :workers, default: 4; end; class RGoConfigStaging < RGoConfigBase; end; RGoConfigBase.configure { |config| config.log_level = :warn }; RGoConfigProduction.configure { |config| config.log_level = :error; config.database.pool = 20; config.workers = 8 }; puts [RGoConfigBase.config.log_level, RGoConfigBase.config.database.pool, RGoConfigProduction.config.log_level, RGoConfigProduction.config.database.pool, RGoConfigProduction.config.workers, RGoConfigStaging.config.log_level, RGoConfigStaging.config.database.pool].join(":")' 'warn:5:error:20:8:info:5'
run_case dry_configurable_update 'require "dry/configurable"; class RGoConfigUpdate; extend Dry::Configurable; setting :timeout, default: 5; setting :auth do; setting :token, default: "none"; setting :scheme, default: "bearer", constructor: ->(value) { value.capitalize }; end; end; RGoConfigUpdate.config.update(timeout: 30, auth: {token: "abc", scheme: "basic"}); puts [RGoConfigUpdate.config.timeout, RGoConfigUpdate.config.auth.token, RGoConfigUpdate.config.auth.scheme].join(":")' '30:abc:Basic'
run_case dry_configurable_finalize 'require "dry/configurable"; class RGoConfigFinalize; extend Dry::Configurable; setting :name, default: "rgo"; setting :nested do; setting :value, default: "inside"; end; end; RGoConfigFinalize.finalize!(freeze_values: true); errors = []; begin; RGoConfigFinalize.config.name = "changed"; rescue Dry::Configurable::FrozenConfigError; errors << :top; end; begin; RGoConfigFinalize.config.nested.value = "changed"; rescue Dry::Configurable::FrozenConfigError; errors << :nested; end; puts [RGoConfigFinalize.config.frozen?, RGoConfigFinalize.config.name.frozen?, RGoConfigFinalize.config.nested.frozen?, RGoConfigFinalize.config.nested.value.frozen?, errors.join(",")].join(":")' 'true:true:true:true:top,nested'
run_case dry_schema_params 'require "dry/schema"; schema = Dry::Schema.Params { required(:email).filled(:string); required(:age).filled(:integer, gt?: 18) }; good = schema.call("email" => "a@b", "age" => "42"); bad = schema.call("email" => "", "age" => "17"); puts [good.success?, good.to_h[:age], bad.errors.to_h[:age].first].join("|")' 'true|42|must be greater than 18'
run_case dry_schema_nested 'require "dry/schema"; schema = Dry::Schema.Params do; required(:profile).hash { required(:name).filled(:string) }; required(:users).array(:hash) { required(:email).filled(:string); optional(:age).value(:integer) }; end; good = schema.call("profile" => {"name" => "Ruby"}, "users" => [{"email" => "a@b", "age" => "21"}]); bad = schema.call("profile" => {}, "users" => [{"email" => ""}]); puts [good.success?, good.to_h[:users][0][:age], bad.errors.to_h[:users][0][:email].first].join("|")' 'true|21|must be filled'
run_case dry_validation_contract 'require "dry/validation"; class RGoSignupContract < Dry::Validation::Contract; params do; required(:email).filled(:string); required(:age).filled(:integer); end; rule(:email) { key.failure("must contain @") unless value.include?("@") }; rule(:age) { key.failure("must be adult") if value < 18 }; end; contract = RGoSignupContract.new; good = contract.call("email" => "a@b", "age" => "21"); bad = contract.call("email" => "bad", "age" => "17"); puts [good.success?, good.to_h[:age], bad.errors.to_h[:email].first, bad.errors.to_h[:age].first].join("|")' 'true|21|must contain @|must be adult'
run_case dry_monads_result_maybe 'require "dry/monads"; include Dry::Monads[:result, :maybe]; ok = Success(21).fmap { |value| value * 2 }; recovered = Failure(:missing).or { Success(7) }; some = Maybe("ruby").fmap(&:upcase); none = Maybe(nil); puts [ok.value!, recovered.value!, some.value!, none.none?].join("|")' '42|7|RUBY|true'
run_case rspec_expectation_matchers 'require "rspec/expectations"; include RSpec::Matchers; expect(20 + 22).to eq(42); expect([1, 2, 3]).to include(2); expect { raise ArgumentError, "bad" }.to raise_error(ArgumentError, /bad/); puts "value|include|raise"' 'value|include|raise'
run_case rspec_mock_double 'require "rspec/mocks"; require "rspec/expectations"; include RSpec::Mocks::ExampleMethods; include RSpec::Matchers; RSpec::Mocks.setup; service = double("service"); allow(service).to receive(:fetch).with(2).and_return(42); expect(service.fetch(2)).to eq(42); expect(service).to have_received(:fetch).with(2); RSpec::Mocks.verify; puts "stub|args|received"; RSpec::Mocks.teardown' 'stub|args|received'
run_case aws_sdk_s3_stubbed_requests 'require "aws-sdk-s3"; client = Aws::S3::Client.new(region: "us-east-1", stub_responses: true); client.stub_responses(:put_object, etag: "abc"); client.stub_responses(:get_object, body: "payload", etag: "abc"); put = client.put_object(bucket: "bucket-name", key: "key", body: "payload", metadata: {"x" => "y"}); get = client.get_object(bucket: "bucket-name", key: "key"); puts [put.etag, get.body.read, get.etag, client.api_requests.map { |request| request[:operation_name] }.join(",")].join("|")' 'abc|payload|abc|put_object,get_object'
run_case prawn_two_page_pdf 'require "prawn"; pdf = Prawn::Document.new; pdf.text "Hello"; pdf.start_new_page; pdf.text "Page 2"; bytes = pdf.render; puts [bytes.start_with?("%PDF-1."), bytes.end_with?("%%EOF\n"), bytes.include?("/Count 2"), pdf.page_count].join("|")' 'true|true|true|2'

echo "gem compatibility: $passed passed, $failed failed"
if [ "$mode" = "--strict" ] && [ "$failed" -ne 0 ]; then
	exit 1
fi
