name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.3

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -race -covermode atomic -coverprofile=covprofile ./...

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go get github.com/mattn/goveralls
        go install github.com/mattn/goveralls
        goveralls -coverprofile=covprofile -service=github
